# Dockerfile for building a light version of the application.
# - GridLAB-D and all associated tools will not be included (e.g.
#   Xerces, MySQLConnector/C, etc.)
# - pyvvo will be pip installed, rather than just being copied in.

# Use the GridAPPS-D base container.
FROM gridappsd/app-container-base:develop

# Borrow a page from here:
# https://github.com/GRIDAPPSD/gridappsd-python/blob/develop/Dockerfile
WORKDIR /usr/src/pyvvo

# Copy in requirements and install them.
COPY requirements.txt setup.py ./
RUN pip install --no-cache-dir -r requirements.txt

# Add PyVVO application files.
ARG PYVVO_ARCHIVE
ADD ${PYVVO_ARCHIVE} /usr/src/pyvvo

# Pip install pyvvo and remove the source files.
RUN pip install . \
    && cd / \
    && rm -rf /usr/src/pyvvo

# Work from root I suppose
WORKDIR /