version: "3.7"

services:
  pyvvo:
    image: gridappsd/pyvvo:latest
    environment:
      DB_HOST: 'db'
      DB_USER: 'pyvvo'
      DB_PASS: 'pyvvo'
      DB_DB: 'pyvvo'
      DB_PORT: "3306"
    depends_on:
      - db
  db:
    image: gridappsd/pyvvo-mysql:latest
    volumes:
      - db_volume:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: 'pyvvo'
      MYSQL_USER: 'pyvvo'
      MYSQL_PASSWORD: 'pyvvo'
    expose:
      - "3306"

volumes:
  db_volume: {}

